Proyecto/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include, re_path
from django.conf.urls import url
from django.conf.urls.static import static
from exp4 import views
from Proyecto.views import home, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
	path('app/registro_mascotas', views.registro_mascotas, name='registro_mascotas'),
    path('app/listar_mascotas', views.listar_mascotas, name='listar_mascotas'),
    path('app/detalle/<int:id>/', views.detalle_mascotas, name='detalle_mascotas'),
    path('app/detalle/mascota/<int:id>/', views.editar_mascotas, name='editar_mascotas'),
    path('app/eliminar/<int:pk>/delete/', views.EliminarForm.as_view(), name='eliminar-mascotas'),
    path('', home, name='home'),
    url(r'^app/logout/$', logout_view, name='logout_view'),
    path('exp4/', include('exp4.urls', namespace='exp4')),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    url(r'^auth/', include('rest_framework_social_oauth2.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exp4/urls.py
from django.conf.urls import url
from Proyecto.views import login_form
# SET THE NAMESPACE!
app_name = 'exp4'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[

    url(r'^app/login/$',login_form, name='login_form'),
]

usuarios/urls.py
from django.conf.urls import url

from usuarios.views import RegistroUsuario, UserAPI

app_name = 'usuarios'

urlpatterns = [
	url(r'^registrar', RegistroUsuario.as_view(), name="registrar"),
	url(r'^api', UserAPI.as_view(), name="api"),

]

exp4/models.py
from django.db import models



GENERO_CHOICES = (
    ('M', 'Macho'),
    ('H', 'Hembra'),
)

class Tipo(models.Model):
	descripcion = models.TextField(verbose_name='descripcion')

	def __str__(self):
		return (self.descripcion)


class Gato(models.Model): #Tabla Gato
	nombre_gato = models.TextField()
	genero = models.CharField(max_length=1, choices=GENERO_CHOICES, verbose_name='genero')
	edad = models.PositiveSmallIntegerField(default=0, verbose_name='edad')
	fecha_registro= models.DateTimeField(auto_now=True)
	tipo= models.ForeignKey(Tipo, on_delete=models.PROTECT)
	imagen = models.ImageField(upload_to='imagenes/rescatados/') # Requiere libreria Pillow

	def __unicode__(self):
		return str(self.imagen)


class Socio(models.Model):
	rut = models.TextField()
	nombres = models.TextField()
	apellido_mat = models.TextField()
	apellido_pat = models.TextField()
	direccion = models.TextField()
	telefono = models.TextField()
	email = models.TextField()
	edad = models.PositiveSmallIntegerField(default=0, verbose_name='edad')

class Adopcion(models.Model):
	gato = models.ForeignKey(Gato, on_delete=models.PROTECT)
	socio = models.ForeignKey(Socio, on_delete=models.PROTECT)
	fecha_adopcion = models.DateTimeField(auto_now=True)

usuarios/models.py
from django.db import models

# Create your models here.

Proyecto/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput())

usuarios/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistroForm(UserCreationForm):

	class Meta:
		model = User
		fields = [
				'username',
				'first_name',
				'last_name',
				'email',
				'password',
			]
		labels = {
				'username': 'Nombre de usuario',
				'first_name': 'Nombre',
				'last_name': 'Apellidos',
				'email': 'Correo',
				'password': 'Contraseña',
		}

Proyecto/views.py
from django.template import RequestContext
from django.shortcuts import render, redirect
from Proyecto.forms import LoginForm
from django.contrib.auth import authenticate, login, logout

from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required



 
def login_form(request):
    message= None
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username=request.POST.get('username')
            password=request.POST.get('password')

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('home'))
                else:
                    return HttpResponse("Cuenta Inactiva.")
            else:
                message ="Nombre Usuario y/o Contraseña incorrecta"

    else:
        form = LoginForm()
    return render(request,'formularios/login.html', {'message=':message ,'form': form})



def home(request):
    return render(request,'inicio.html')

@login_required
def logout_view(request):
    logout(request)
    return render(request,'inicio.html')

exp4/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect	
from django.template import RequestContext
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.generic import DeleteView,FormView
from django.urls import reverse_lazy

from exp4.models import Gato, Socio
from exp4.form import RegistroForm, actualizaMascota

@login_required
def registro_mascotas(request):
	if request.method =='POST': # si peticion es POST
		form = RegistroForm(request.POST, request.FILES) # Inicializa objeto form pasando el contenido (request)
		if form.is_valid(): # valida formulario --> CSRF
			mascota = Gato(
							nombre_gato=form.cleaned_data['nombre_gato'],
							genero=form.cleaned_data['genero'],
							edad=form.cleaned_data['edad'],
							tipo=form.cleaned_data['tipo'],
							imagen=form.cleaned_data['imagen']
						   )
			mascota.save()
			return redirect('registro_mascotas')# carga pagina creala urls
	else:
		form = RegistroForm()
	return render(request,'formularios/registro_mascotas.html', {'form': form})

@login_required
def listar_mascotas(request):
	mascotas = Gato.objects.all()
	return render(request,'list/listar_mascotas.html', {'mascotas': mascotas})

@login_required
def detalle_mascotas(request, id):
	mascota = get_object_or_404(Gato, pk=id)
	return render(request,'list/detalle_mascotas.html', {'mascota': mascota})

@login_required
def editar_mascotas(request, id):
	mascota = get_object_or_404(Gato, pk=id)
	if request.method =='POST': # si peticion es POST
		form = actualizaMascota(request.POST, instance=mascota) # Inicializa objeto form pasando el contenido (request)
		if form.is_valid(): # valida formulario --> CSRF
			form.save()
			return redirect('detalle_mascotas', id)# carga pagina creala urls
	else:
		form = actualizaMascota(instance=mascota)
	return render(request,'formularios/editar_mascotas.html', {'form': form})


class EliminarForm(DeleteView):
	model = Gato
	template_name = 'exp4/gato_confirm_delete.html'
	success_url = reverse_lazy('listar_mascotas')

usuarios/views.py
import json
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy

from usuarios.forms import RegistroForm
from usuarios.serializers import registro_usuario

class RegistroUsuario(CreateView):
	model = User
	template_name = "formularios/registrar.html"
	form_class = RegistroForm
	success_url = reverse_lazy('home')


class UserAPI(APIView):
	def post(self, request):
		serializer = registro_usuario(data = request.data) # Inicializa objeto form pasando el contenido (request)
		if serializer.is_valid(): # valida formulario --> CSRF
			user = serializer.save()
			return Response(serializer.data, status = status.HTTP_201_CREATED)
		else:
			return Response(serializer.errors, status = status.HTTP_400_BAD_REQUEST)	

exp4/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
    	{% block css %}
			<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
		  {% endblock css %}

        <title>Aplicacion Rescate Mascotas | {% block title %}{% endblock %}</title>

    </head>
    <body>
    	
   		<nav class="light-blue accent-4">
    			<div class="nav-wrapper">
      				<a href="#" class="brand-logo">Rescate Mascotas</a>
      				<a href="#" data-target="menu-reponsivo" class="sidenav-trigger">
      					<i class="material-icons">menu</i></a>

      					<ul id="nav-mobile" class="right hide-on-med-and-down">
        				<li><a href="{% url 'home' %} ">Inicio</a></li>
        		 		{% if user.is_authenticated %}	
        				<li><a href="{% url 'registro_mascotas' %}">Registro Mascotas</a></li>
        				<li><a href="{% url 'listar_mascotas' %}">Listar Mascotas</a></li>
        				<li><a href="{% url 'logout_view' %}">Salir</a></li>
        		 		{% else %}
   						<li><a href="{% url 'exp4:login_form' %}">Login</a></li>
      			 		{% endif %}	
      					</ul>
    			</div>

  		</nav>

  		
  		<ul class="sidenav" id="menu-reponsivo">
	  		<li class="light-blue accent-4 center-align">
	  			<a class="#ffffff white-text " href="{% url 'home' %}">INICIO</a>
	  		</li>
	  		<li class="light-blue accent-4 center-align">
	  			<a class="#ffffff white-text" href="{% url 'registro_mascotas' %}">REGISTRO MASCOTAS</a>
	  		</li>
	  		<li class="light-blue accent-4 center-align">
	  			<a class="#ffffff white-text" href="{% url 'listar_mascotas' %}">LISTAR MASCOTAS</a>
	  		</li>
	  		<li class="light-blue accent-4 center-align">
	  			<a class="#ffffff white-text" href="{% url 'exp4:login_form' %}">LOGIN</a>
	  		</li>
		</ul>


    		{% block content %}{% endblock %}



  <footer class="page-footer" style="background-color: #00acc1;">
    <div class="container">
      <div class="row">
        <div class="col xl6 offset-xl3 l6 offset-l3  m8 offset-m2 s10 offset-1">
          <h5 class="grey-text text-lighten-3 center">RESCATE MASCOTAS</h5>
          El Sitio Web de Rescates de Mascotas en Chile. <blockquote>By Lagos Zelada | Equipo</blockquote>
          <p><i class="material-icons center left">mail</i> rlagosj@gmail.com</p>
          <p><i class="material-icons center left">phone</i>9990354600</p>
        </div>

      </div>
    </div>
    <div class="footer-copyright teal lighten-2">
      <div class="container">
        Copyright &copy; 2018
        <a href="#!" class="grey-text text-lighten-3 right"><i class="material-icons red-text accent-2 left">favorite_border</i>
          Hecho con amor</a>
      </div>
    </div>

  </footer>
 	{% block javascript %}
		<script
		src="https://code.jquery.com/jquery-3.3.1.min.js"
		integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
		crossorigin="anonymous"></script>

 <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.js"></script>
		<script>
		
		$(document).ready(function(){

		// Initialize materialize data picker
		$('.datepicker').datepicker({'format': 'yyyy-mm-dd'});
		$('select').formSelect();

    $('.carousel').carousel({
                            });

    $('.sidenav').sidenav();

		});

  		document.addEventListener('DOMContentLoaded', function() {
    	var elems = document.querySelectorAll('.sidenav');
    	var instances = M.Sidenav.init(elems, options);
  		});

		   var options = {}

    	document.addEventListener('DOMContentLoaded', function() {
		  var elems = document.querySelectorAll('.slider');
		  var instances = M.Slider.init(elems, options);
		  });

  window.fbAsyncInit = function() {
    FB.init({
      appId      : '2062834107143102',
      xfbml      : true,
      version    : 'v3.2'
    });
    FB.AppEvents.logPageView();
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/es_ES/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

function checkLoginState() {
  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });
}

FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
});

FB.login(function(response) {
  // handle the response
}, {scope: 'public_profile,email'});

  	</script>
	{% endblock javascript %}
    </body>
</html>

exp4/templates/contact_form/contact_form.html
{{ body }}

exp4/templates/contact_form/contact_form_sent.html
<p>Message sent!</p>

exp4/templates/contact_form/test_callable_template_name.html
Callable template_name used.

exp4/templates/exp4/gato_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<center>
<h3>Eliminar Mascota</h3>
</center>
    <div class="container">
	    <form method="post" action="" class="col s12">{% csrf_token %}
	    <p>Seguro Eliminar? "{{ object }}"?</p>

			    <div class='row'>
				      <button type='confirm' name='btn_login' class='btn btn-danger'>Eliminar</button>
				</div>




		</form>
	</div>
{% endblock %}

exp4/templates/formularios/editar_mascotas.html
{% extends "base.html" %}
{% block title %}Editar Datos Mascotas{% endblock %}
{% block head %}Editar Datos Mascota: {{mascota.nombre_gato}} {% endblock %}
{% block content %}
<center>
<h3>Editar Informacion</h3>
</center>
    <div class="container">
	    <form method="post" action="" class="col s12">{% csrf_token %}
	    {% include "formularios/form_snippets.html" %}

			    <div class='row'>
				      <button type='submit' name='btn_login' class='btn waves-effect waves-light col s6 m3'>Enviar</button>
				</div>




		</form>
	</div>
{% endblock %}

exp4/templates/formularios/form_snippets.html
    <div class="row col s12">
        <div class="input-field col s6">
        {% for field in form %}
        	<div class="field.container">
        		{{ field.errors }}
        		{{ field.label_tag }} </br>
        		{{ field }}
        	</div>
        {% endfor %}
    	</div>
	</div>

exp4/templates/formularios/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
    <div class="container">
	<h1>Login</h1>
	{% if message %}
	<b>{{message}}</b>
	{% endif%}


    <form method="post" action="" class="login-form form col s12">{% csrf_token %}
	{% include "formularios/form_snippets.html" %}

              <div class='row'>
                <button type='submit' name='btn_login' class='btn waves-effect waves-light btn'>Entrar</button>

	         	<a class='btn waves-effect waves-light btn' href="{% url 'usuarios:registrar' %}">Registrarse</a>

	         	
	         	<a href="{% url 'social:begin' 'google-oauth2' %}">
	         		<button type='button' name='button' class='btn btn-primary'>Google+</button>
	         	</a>
	         	
	         	<a href="{% url 'social:begin' 'gitLab' %}">
	         		<button type='button' name='button' class='btn btn-primary'>GitLab</button>
	         	</a>


              </div>
   
   <div id="spinner"
			    style="
			        background: #4267b2;
			        border-radius: 5px;
			        color: white;
			        height: 40px;
			        text-align: center;
			        width: 250px;">
						    <div
						    class="fb-login-button"
						    data-max-rows="1"
						    data-size="large"
						    data-button-type="continue_with"
						    data-use-continue-as="true"
						    ></div>
	</div>   


    </form>
	</div>
{% endblock %}

exp4/templates/formularios/registrar.html
{% extends 'base.html' %}

{% block content %}
<center>
<h3>Registro Usuarios</h3>
</center>

<form method="post">
	{% csrf_token %}
<div class="container">	
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label>Nombre</label>
				<input class="form-control" type="text" name="first_name">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Apellidos</label>
				<input class="form-control" type="text" name="last_name">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Nombre de usuario</label>
				<input class="form-control" type="text" name="username">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Correo</label>
				<input class="form-control" type="text" name="email">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Contraseña</label>
				<input class="form-control" type="password" name="password1">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Confirmar contraseña</label>
				<input class="form-control" type="password" name="password2">
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary "type="submit">Guardar</button>
			</div>
		</div>
	</div>
	</div>
</form>
{% endblock %}

exp4/templates/formularios/registro_mascotas.html
{% extends "base.html" %}
{% block title %}Formulario Registro Mascotas{% endblock %}
{% block head %}Registro Mascotas{% endblock %}
{% block content %}
<center>
<h3>Registro Mascotas</h3>
</center> 
    <div class="container">
	    <form enctype="multipart/form-data" method="post" action=""  class="col s12">{% csrf_token %}
			{% include "formularios/form_snippets.html" %}
	
              <div class='row'>
                <button type='submit' name='btn_login' class='btn waves-effect waves-light btn"'>Enviar</button>
              </div>
		    </form>




 	</div>
{% endblock %}

exp4/templates/inicio.html
{% extends "base.html" %}
{% load static %}
{% load carousel_tag %}

{% block content %}
	 <div class="row light-blue accent-4" >
		<div class="col12 s12 m12 l12 light-blue accent-4" align="center" >	    
		  <div class="slider">
			<ul class="slides">
			  <li>
				<img src= "{% static 'imagenes/adoptados/Duque.jpg' %}"> <!-- random image -->
				<div class="caption center-align">
				  <h3>Perro</h3>
				  <h5 class="light grey-text text-lighten-3 ">Es un Perro</h5>
				</div>
			  </li>
			  <li>
				<img src="{% static 'imagenes/adoptados/Apolo.jpg' %}"> <!-- random image -->
				<div class="caption left-align">
				  <h3>Perro</h3>
				  <h5 class="light grey-text text-lighten-3">Este es un Perro</h5>
				</div>
			  </li>
			  <li>
				<img src="{% static 'imagenes/adoptados/Tom.jpg' %}"> <!-- random image -->
				<div class="caption right-align">
				  <h3>Perro</h3>
				  <h5 class="light grey-text text-lighten-3">Este es un Perro</h5>
				</div>
			  </li>
			</ul>
		  </div>
		</div>

		<div class="col12 s12 m12 l12 light-blue accent-4 hide-on-med-and-down" align="center" >
			<div class="row">
				<div class="col s12">
				  <div>
					<span class="white-text">
						<h5>Rescate y Adopciòn de Mascotas</h5>
					</span>
				  </div>
				</div>
			</div>
		</div>
		
	</div>	
	<div class="row" >
		<div class="col s12 m6 l6 ">
			 <div class="row">
				<div class="col s12 right-align">
				  <div class="card">
					<div class="card-action">
						<h5>Rescate</h5>
						<h6>ETAPA UNO</h6>
					</div>
					<div class="card-content">
					  <p>Rescatamos perros en situacion de peligro y/o abandono. los rehabilitamos y preparamos para buscarles un hogar</p>
					</div>
					 <img src="{% static 'img/rescate.jpg' %}">
				  </div>
				</div>
			  </div>
		</div>
		<div class="col s12 m6 l6 ">
			 <div class="row">
				<div class="col s12 left-align">
				  <div class="card">
				   <img width="50%" src="{% static 'img/crowfunding.jpg' %}" >
					<div class="card-action">
						<h5>CROWFUNDING</h5>
						<h6>FINANCIAMIENTO</h6>
					</div>
					<div class="card-content">
					  <p>Sigue nuestras redes sociales para informarte acerca de las diversas campañasy actividades que realizamos para optener financiamiento para seguir ayudando</p>
					</div>
					<a class="waves-effect waves-light btn">CAMPAÑAS</a>
				  </div>
				</div>
			  </div>
		</div>
		<div class="container section">
			{% carousel %}
		</div>
	</div>
{% endblock %}

exp4/templates/list/carousel.html
			<div class="row">


				<div class="carousel">
			
					<p><h3 class="col s12 m12 pulse blue darken-3 center white-text"> ¡¡¡ADOPTAME!!! 
</h3>		</p>
		  			 {% for imagen in carousel %}
		  			 	
		  		     	<a class="carousel-item" href="#" ><img  src="/media/{{imagen.imagen}}"><h6 class="center">{{imagen.nombre_gato}}</h6></a> 

    				{% endfor %}
				</div>
			</div>

exp4/templates/list/detalle_mascotas.html
{% extends "base.html" %}
{% block title %}Informacion Mascota{% endblock %}
{% block head %}{{mascota.nombre_gato}} {% endblock %}
{% block content %}
    <div class="container">
       <div class="section col s12">
          <ul class="collection with-header">
    {% if mascota.nombre_gato %}
      	     <li class="collection-header"><h5>Nombre: {{mascota.nombre_gato}}</h5></li>
             <li class="collection-item">Fecha Registro: {{mascota.fecha_registro}}</li>
      	     
      	     <li class="collection-item">Edad: {{mascota.edad}}</li>
      	     <li class="collection-item">Genero: {{mascota.genero}}</li>
             <li class="collection-item">Tipo: {{mascota.tipo}}</li>
    {% else %}
    	       No registra Nombre
    {% endif %}
	         </ul>
	 <p>
<center>
              <a class='btn waves-effect waves-light col s6 m3' href="{% url 'listar_mascotas' %}">Volver</a>
	         	<a class='btn waves-effect waves-light btn' href="{% url 'editar_mascotas' mascota.id %}">Editar</a>
</center>
	         </p>
        </div>
      </div>

{% endblock %}

exp4/templates/list/listar_mascotas.html
{% extends "base.html" %}
{% block title %}Listado Mascotas{% endblock %}
{% block head %}Mascotas{% endblock %}
{% block content %}
<div class="container">
    	<div class="section col s12">
  <ul class="collection with-header">
      	     <li class="collection-header"><h4>Listado Mascotas</h4></li>
    {% for mascota in mascotas %}
      <li class="collection-item"> 
      	<a href="{% url 'detalle_mascotas' mascota.id %}"><img width="150" src="/media/{{ mascota.imagen}}"></a> 
      	<a href="{% url 'eliminar-mascotas' mascota.id %}" class="secondary-content"><i class="material-icons">delete</i></a>
      </li>
    {% endfor %}
  </ul>  
</div></div>
{% endblock %}